### ISSUE TITLE
npm start not working

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/kurir-app-server#10]
<img width="721" alt="screen shot 2018-01-19 at 13 58 21" src="https://user-images.githubusercontent.com/12825389/35138390-df7c8242-fd20-11e7-882e-501cc1ad88e4.png">

bisa bantu kira- kira kenapa? @andy-shi88

**Comment by andy-shi88** [comment]
bisa lihat baris 40 codenya di `UserController`? @bhirmbani

**Comment by bhirmbani** [comment]
sama dengan yg di pull dari branch es6

**Comment by andy-shi88** [comment]
node version @bhirmbani ?

**Comment by bhirmbani** [comment]
oh iya, harus pakai node versi support async. tadi pakai version 6.4.0. sekarang sudah npm install lagi pake versi node 8.1.2 dan berfungsi. thank you! 👍
