### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by andy-shi88** [gamantha/kurir-app-server#11]
For revocation needs, we need to save the token since it does not generated with lifetime support.
[OPEN FOR DISCUSSION]
here is what we need to keep:
table: `access_token`
field:
 - id
 - access_token
 - user_id
 - created_at
 - updated_at
 - user_agent [up for discussion]
 - refresh_token [up for discussion]

consideration:
- user_agent: with this user will be able to login from multiple devices, and logout device B from device A. and see list of logged in devices.
- refresh_token: with this we can assign life time of a token, and pass refresh token for exchanging new token, may not be needed if: a. we assign forever lifetime token, b. re login if token lifetime out.

consideration of creating the table:
1. with forever lifetime token it's dangerous as we can't revoke the user out in case user phone get stolen.
2. without saving the token we can't do multiple login well [we can't revoke]

cons:
1. may need more time for authentication as we will check db for every protected request.

**Comment by andy-shi88** [comment]
@kru , @bhirmbani , let's discuss about the above requirements.

**Comment by bhirmbani** [comment]
any other way so we didn't have to check db for every protected req?

**Comment by andy-shi88** [comment]
yes, from what I see the previous implementation is like that, so we just verify the `JWT` and make sure it's valid to our secret key. This way is not secure for some reasons I stated above.
which is why I propose this solution of storing `access_token`

**Comment by bhirmbani** [comment]
So, otherwise we must save it on db. Its okay in my opinion. I think user_agent and refresh_token will be good to implement if only that not make a lot of development time. Also, we must make convention, is it `userId` or `user_id` for field name?

**Comment by andy-shi88** [comment]
I'll follow the implemented convention @bhirmbani  I'll use camel case for this 👍

**Comment by kru** [comment]
The database table should be plural `access_tokens`.  If we will using `refresh_token` make sure we handle it properly on mobile. Do We need to specify how much devices can log in within a user account?

**Comment by andy-shi88** [comment]
as alternative to refresh token, we can add unlimited lifetime to the token thou, it should be the same if I don't miss anything.

**Comment by kru** [comment]
refresh token is good then as the consideration related to security for the end user.
