### ISSUE TITLE
Edit profile

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/kurir-app-server#50]
- [x] change association between User and Sender
- [x] method to edit user profile
- [x] migration file to reflect models change
- [x] send confirmation email only for sender role
- [x] test

Reference:
![image](https://user-images.githubusercontent.com/12825389/36516237-acb9715e-17af-11e8-87d2-9fdbe611815e.png)

**Comment by andy-shi88** [comment]
ini udah done, on going atau todo @bhirmbani ?

**Comment by bhirmbani** [comment]
ini uda done, bisa langsung di review
