### ISSUE TITLE
Shipping details

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/kurir-app-server#52]
### WHAT

Dikarenakan admin diharuskan bisa melihat shipping details per KA-11, maka perlu ada perombakan model item yang disesuaikan dengan spesifikasi shipping details.

####  Shipping details requirement
1. Info package
2. alamat package
3. tujuan package
4. status package
5. history (jam berapa di pickup, oleh kurir siapa, dll)

### PROPOSAL
1. post request to create one item
2. get request all item

**Comment by andy-shi88** [comment]
ini harusnya sama perombakan pas aku create item endpoint udah done ya? @bhirmbani kalau confirm nanti di close ya

**Comment by bhirmbani** [comment]
ini kutambahin ReceiverId dulu ya pas waktu create item @andy-shi88

**Comment by andy-shi88** [comment]
maksudnya `ReceiverId` jadi payload pas `post api/item` ?

**Comment by bhirmbani** [comment]
iya @andy-shi88 , jadi bikin model Receiver dulu

**Comment by bhirmbani** [comment]
https://github.com/gamantha/kurir-app-server/tree/feature/shipping-details

**Comment by bhirmbani** [comment]
[api-changes branch in github/linguist](/github/linguist/tree/api-changes)
