### ISSUE TITLE
Create item endpoint

### ISSUE THREAD

**Issue by bhirmbani** [gamantha/kurir-app-server#53]
### What
endpoint untuk create item perlu diperbaiki, mengikuti acuan invision yang ada.

### Reference

No Screen | Screen
------------ | -------------
1 (from, to, weight, estimasi biaya) | ![image](https://user-images.githubusercontent.com/12825389/36658949-526316ac-1b05-11e8-8783-2e3b3fff4b03.png)
2 (country, city, address) | ![image](https://user-images.githubusercontent.com/12825389/36658970-6aa1f2ce-1b05-11e8-8895-cb981c7c0b0a.png)
3 (model Receiver) | ![image](https://user-images.githubusercontent.com/12825389/36659000-85f107fe-1b05-11e8-940d-acd9abf072d8.png)
4 | ![image](https://user-images.githubusercontent.com/12825389/36659169-1740a26e-1b06-11e8-8001-9a85b03fd9f4.png)
5 | ![image](https://user-images.githubusercontent.com/12825389/36659184-297d620a-1b06-11e8-8867-c9e61cf38651.png)
6 (saat user click From dan To Input) | ![image](https://user-images.githubusercontent.com/12825389/36672824-55af702a-1b33-11e8-9be8-c168d476deaa.png)

### What to do
1. estimasi biaya.
2. generate ticket number dengan format: KA-${randomNum}
3. create item endpoint
4. implementasi list kota untuk screen 6 (mungkin bisa dari view/backend?)

**Comment by bhirmbani** [comment]
Buat migrasi dan model sudah ku buatkan base nya. kamu bisa mulai mengerjakan issue ini dari branch feature/create-item ya, @andy-shi88 

beberapa commit nya bakal ada dari branch feature/edit-profile yang belum di merge, jadi mudah-mudahan ga ada konflik.

jangan lupa untuk menjalankan file migration nya jika ingin menjalankan test.

link branch: https://github.com/gamantha/kurir-app-server/tree/feature/create-item

**Comment by andy-shi88** [comment]
noted @bhirmbani

**Comment by andy-shi88** [comment]
done:
