### ISSUE TITLE
Register with Email - duplicate user

### ISSUE THREAD

**Issue by andy-shi88** [gamantha/kurir-app-server#8]
Current implementation still create duplicate user if we pass in the same email. It should be unique with no duplication of email.

**Comment by bhirmbani** [comment]
@andy-shi88 kenapa ya kalo saya import models dari file baru, misal helpers/uniquevalidator.js , model nya ga bisa diakses. tapi kalau dari file lain bisa?

**Comment by andy-shi88** [comment]
udah di push codenya? kalau udah saya coba cek @bhirmbani

**Comment by bhirmbani** [comment]
@andy-shi88 sudah. di PR #9
